###
# @name signup
post http://localhost:5000/api/user/register
Content-Type: application/json

{
    "first_name": "test jr.",
    "last_name": "tester",
    "email": "testjr@devygroup.net",
    "password":"securepassword"
}

### 
# @name login
post http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email": "{{signup.request.body.email}}",
    "password":"{{signup.request.body.password}}"
}

###
# @name loginTokenTest
@authToken = {{login.response.body.accessToken}}
get http://localhost:5000/api/user/test
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "email": "{{signup.request.body.email}}"
}

###
@refreshToken = {{login.response.body.refreshToken}}
# @name refresh
POST http://localhost:5000/api/user/refresh 
Content-Type: application/json

{
    "token":"{{refreshToken}}"
}

###
# @name refreshTokenTest
@newAuthToken = {{refresh.response.body.accessToken}}
get http://localhost:5000/api/user/test
Authorization: Bearer {{newAuthToken}}
Content-Type: application/json

{
    "email": "{{signup.request.body.email}}"
}

###
# @name logout
@storedAuthToken = {{refreshTokenTest.response.body.token}}
delete http://localhost:5000/api/user/logout
Authorization: Bearer {{storedAuthToken}}
Content-Type: application/json

{
    "email": "{{signup.request.body.email}}"
}

###
# @name logoutTest
get http://localhost:5000/api/user/logoutTest
Content-Type: application/json

{
    "email": "{{signup.request.body.email}}"
}

